# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pdf_to_csv.ui',
# licensing of 'pdf_to_csv.ui' applies.
#
# Created: Sun Mar 15 11:10:27 2020
#      by: pyside2-uic  running on PySide2 5.12.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form_name(object):
    def setupUi(self, Form_name):
        Form_name.setObjectName("Form_name")
        Form_name.resize(363, 192)
        self.pushButton = QtWidgets.QPushButton(Form_name)
        self.pushButton.setGeometry(QtCore.QRect(140, 80, 171, 31))
        self.pushButton.setObjectName("pushButton")
        self.toolButton = QtWidgets.QToolButton(Form_name)
        self.toolButton.setGeometry(QtCore.QRect(320, 30, 25, 19))
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(Form_name)
        self.toolButton_2.setGeometry(QtCore.QRect(320, 60, 25, 19))
        self.toolButton_2.setObjectName("toolButton_2")
        self.layoutWidget = QtWidgets.QWidget(Form_name)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 29, 301, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setClearButtonEnabled(False)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout.addWidget(self.lineEdit_5)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.layoutWidget1 = QtWidgets.QWidget(Form_name)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 80, 121, 31))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_4.addWidget(self.lineEdit)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.label_3 = QtWidgets.QLabel(Form_name)
        self.label_3.setGeometry(QtCore.QRect(70, 140, 231, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(Form_name)
        self.label_6.setGeometry(QtCore.QRect(150, 160, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Form_name)
        QtCore.QMetaObject.connectSlotsByName(Form_name)

    def retranslateUi(self, Form_name):
        Form_name.setWindowTitle(QtWidgets.QApplication.translate("Form_name", "EXTRACT TABLE FROM PDF TO EXCEL", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("Form_name", "Extract", None, -1))
        self.toolButton.setText(QtWidgets.QApplication.translate("Form_name", "...", None, -1))
        self.toolButton_2.setText(QtWidgets.QApplication.translate("Form_name", "...", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Form_name", "File", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Form_name", "Destination", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Form_name", "Page          ", None, -1))
        self.lineEdit.setPlaceholderText(QtWidgets.QApplication.translate("Form_name", "1-10", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Form_name", "© Copyright 2001-2018, Python Software Foundation", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Form_name", "License: LGPL-2", None, -1))

